awsRegion: ${region}

rbac:
  create: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ${role_arn}

autoDiscovery:
  clusterName: ${cluster_name}

serviceMonitor:
  enabled: true
  interval: 10s
  namespace: monitoring
  selector:
    app: kube-prometheus-stack-operator
    release: kube-prometheus-stack
  path: /metrics

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node.kubernetes.io/lifecycle
          operator: In
          values:
            - ondemand

