serviceMonitor:
  enabled: true
  additionalLabels:
    app: kube-prometheus-stack-operator
    release: kube-prometheus-stack

mysql:
  existingSecret: mysql-exporter

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node.kubernetes.io/lifecycle
          operator: In
          values:
            - spot
