name: 'Terraform-utils'

on:
  push:
    branches:
      - 'feature/terraform-utils'
    paths:
      - 'docker/terraform-utils/Dockerfile'

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: docker/terraform-utils/
          tags: maddevsio/terraform-utils:latest
